### ISSUE TITLE
h5py default_file_mode error

### ISSUE THREAD

**Issue by prayshah99** [deepqmc/deepqmc#45]
Whenever I try to run deepqmc from WSL Terminal I am getting the following error. Please help me solve this issue.

Traceback (most recent call last):
  File "/home/pray/myproject/deepqmc/bin/deepqmc", line 5, in <module>
    from deepqmc.cli import cli
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/cli.py", line 14, in <module>
    from .io import wf_from_file
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/io.py", line 9, in <module>
    from .wf import ANSATZES
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/wf/__init__.py", line 4, in <module>
    from .paulinet import PauliNet
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/wf/paulinet/__init__.py", line 6, in <module>
    from .paulinet import PauliNet
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/wf/paulinet/paulinet.py", line 17, in <module>
    from .pyscfext import pyscf_from_mol
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/deepqmc/wf/paulinet/pyscfext.py", line 6, in <module>
    import pyscf.lib.chkfile as chk
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/home/pray/myproject/deepqmc/lib/python3.8/site-packages/pyscf/lib/misc.py", line 46, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 183, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.

**Comment by jhrmnn** [comment]
Thanks for reporting. This was an issue with a version incompatibility of two dependencies, PySCF and H5PY. It was already fixed in the master branch, and I am now releasing 0.3.1 which will include the fix.

**Comment by jhrmnn** [comment]
0.3.1 is live now.

**Comment by prayshah99** [comment]
It's working now. Thank you.
